// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auth

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID       int64
	Email        string
	Password     string
	CreationTime pgtype.Timestamp
}
